test_format = 1.0

[default]

    [default.curl_tests]
    default.logged_on_sso = true

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.compagny_name = "YunoHost"